apiVersion: v1
entries:
  nats-streaming-operator:
  - apiVersion: v1
    appVersion: 0.2.3
    created: "2020-02-26T17:09:49.918929-05:00"
    description: Operator for managing NATS Streaming clusters running on Kubernetes.
    digest: 9f13a1f4c145f4f172e194b85039537a4e3890213ab6e717e9e751be38292f2a
    home: https://github.com/nats-io/nats-streaming-operator
    icon: https://bitnami.com/assets/stacks/nats/img/nats-stack-110x117.png
    keywords:
    - nats
    - streaming
    - delivery
    - ratelimit
    - replay
    - restart
    maintainers:
    - email: hans@starefossen.com
      name: starefossen
    name: nats-streaming-operator
    sources:
    - https://github.com/nats-io/nats-streaming-operator
    urls:
    - https://cogitocorp.github.io/nats-streaming-operator/helm/nats-streaming-operator/nats-streaming-operator-1.0.0.tgz
    version: 1.0.0
generated: "2020-02-26T17:09:49.915815-05:00"
